Make welcome message configurable
rharish101/ReGreet pull request #70
Opened 2024-05-31 03:11 UTC by Eliasin

Hi! Just a small change that closes #49. There are some things that could maybe go back and forth like the `.clone()` at `get_default_message` to reduce `.clone()` at callsites not matching the rest of the config because it returns an owned string but I think the rest should be good.

I was also thinking about a PR that chooses different background images based on aspect ratio/display name (I have a 3:2 laptop screen but plug in a 16:9 monitor that I'd like a different background on), but I know that `cage` can mirror across two screens and I wouldn't know if that would make the feature impossible. I'm not familiar with `relm4` and Wayland development in general so I'm a little fuzzy on what the behaviour would be in that case though I did spot `relm4::abstractions::drawing::DrawHandler::size` so that gives some hope for the possibility of dynamically detecting aspect ratio. 

From what I know to add background based on name would require speaking Wayland (`wl_output::name` unless relm4 or the gtk bindings abstract it) so that might be a dealbreaker since it'd add a lot of complexity. Let me know what you think about either of these ideas, I recognize it might be out of scope or just plain too much work to maintain.

- [x] Docs Updated
- [x] Pre-commit hooks passing

2024-06-03 21:10 UTC, rharish101 requested changes
Everything looks great, except for one tiny little question in the sample config file that I have noted down.

2024-06-03 21:10 UTC, rharish101 commented on regreet.sample.toml
> +greeting_message = "Welcome back!"
Shouldn't this be `greeting_msg`?

2024-06-05 15:06 UTC, rharish101 commented on regreet.sample.toml
> +greeting_message = "Welcome back!"
Fixed this myself, no worries!

2024-06-05 15:06 UTC, merged

2024-06-05 15:20 UTC, rharish101 commented
Thanks for the PR! As for the backgrounds, that sounds like too much complexity to have different background images on different monitors. I'd recommend rather to choose a large 3:2/16:9 wallpaper and use one of the different background fits.

2024-06-05 22:52 UTC, Eliasin commented
Thanks for the quick reply! (and oops on the config)

And thanks for the insight on the background image.